// Generated by LiveScript 1.3.1
angular.module('app').controller('about', ['$scope', '$xonom', 'scroll', '$location', function($scope, $xonom, scroll, $location){
  return $scope.persons = [
    {
      image: 'https://s3.amazonaws.com/uifaces/faces/twitter/jsa/128.jpg',
      name: 'Andrey',
      desc: 'Full stack developer'
    }, {
      image: 'https://s3.amazonaws.com/uifaces/faces/twitter/tomaslau/128.jpg',
      name: 'Vladimir',
      desc: 'Frontend developer'
    }
  ];
}]);