// Generated by LiveScript 1.3.1
angular.module('app').directive('colored', function(){
  return {
    restrict: 'A',
    link: function($scope, $element, $attrs){
      return $attrs.$observe('colored', function(value){
        var tagsToReplace, escape, code, colored, space;
        tagsToReplace = {
          '&': '&amp;',
          '<': '&lt;',
          '>': '&gt;'
        };
        escape = function(tag){
          var ref$;
          return (ref$ = tagsToReplace[tag]) != null ? ref$ : tag;
        };
        code = function(group){
          return "<span class='colored code'>" + group + "</span>";
        };
        colored = function(str, group){
          return "<span class='colored'>" + group + "</span>";
        };
        space = function(str){
          return "<span class='space'></span>";
        };
        return $element.html(value.replace(/[&<>]/g, escape).replace(/ /g, space).replace(/colored\(([^)]+)\)/g, colored).replace(/[(){}]/g, code));
      });
    }
  };
});