// Generated by LiveScript 1.3.1
angular.module('app').directive('landingAnimation', function(){
  return {
    restrict: 'C',
    link: function($scope, $element){
      var win;
      win = $(window);
      return win.scroll(function(){
        var pos, h, s;
        pos = win.scrollTop();
        h = -80 + pos / 5;
        $('.fixed').css('top', h < 0 ? h : 0);
        s = 450 - pos * 2;
        return $('.demo-terminal').css('height', s > 0 ? s : 0);
      });
    }
  };
});