// Generated by LiveScript 1.3.1
angular.module('app').directive('landingAnimation', function(){
  return {
    restrict: 'C',
    link: function($scope, $element){
      var win;
      win = $(window);
      return win.scroll(function(){
        var pos;
        pos = win.scrollTop();
        if (pos < 100) {
          return $('.fixed').removeClass('active');
        } else {
          return $('.fixed').addClass('active');
        }
      });
    }
  };
});