// Generated by LiveScript 1.3.1
angular.module('app').config(['$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider){
  $urlRouterProvider.otherwise('landing');
  return $stateProvider.state('root', {
    url: '',
    views: {
      '': {
        templateUrl: 'app',
        controller: 'app'
      }
    }
  });
}]);