// Generated by LiveScript 1.3.1
angular.module('app').service('observ', ['safeApply', function(safeApply){
  return function(func){
    var observers, notify, scope;
    observers = [];
    notify = function(name, obj){
      var notifyone;
      notifyone = function(item){
        return safeApply(function(){
          return item[1](obj);
        });
      };
      return observers.filter(function(it){
        return it[0] === name;
      }).forEach(notifyone);
    };
    scope = func(notify);
    scope.on = function(name, callback){
      return observers.push([name, callback]);
    };
    scope.off = function(callback){
      var remove;
      remove = function(item){
        var index;
        index = observers.indexOf(item);
        return observers.splice(index, 1);
      };
      return observers.filter(function(it){
        return it[1] === callback;
      }).forEach(remove);
    };
    return scope;
  };
}]);