// Generated by LiveScript 1.3.1
angular.module('app').service('scroll', ['observ', function(observ){
  return observ(function(notify){
    var el, notifyTop;
    el = $(window);
    notifyTop = function(){
      return notify('change', el.scrollTop());
    };
    el.scroll(notifyTop);
    notifyTop();
    return {
      to: function(id){
        var parent;
        parent = $('.scroll');
        parent.animate({
          scrollTop: $('#' + id).offset().top + parent.scrollTop()
        }, 1000);
      }
    };
  });
}]);