// Generated by LiveScript 1.3.1
var path;
path = require('path');
require('xonom').run(function($xonom){
  var tty, app;
  tty = require('tty.js');
  console.log('1');
  app = tty.createServer({
    port: process.env.PORT || 80,
    users: [],
    cwd: require('path').resolve(process.cwd(), '../demo'),
    'static': require('path').resolve(__dirname, '../client'),
    shell: 'bash'
  });
  app.use(require('body-parser').json());
  $xonom.object('$router', app);
  return console.log('2');
}).run(__dirname + "/app/**/*.service.server.js").run(function(){
  return console.log('3');
}).run(__dirname + "/app/**/*.route.server.js").object('p', require('prelude-ls')).object('repo', {
  commands: [],
  docs: []
}).run(function(){
  return console.log('4');
}).run(path.resolve(__dirname, "../node_modules/nixar/compiled-commands") + '/*').run(function(){
  return console.log('5');
}).run(path.resolve(__dirname, "../node_modules/nixar/docs") + '/*').run(function(){
  return console.log('6');
}).run(__dirname + "/xonom.route.js").run(function($router){
  return $router.listen();
});